import { type ChangeEvent, useEffect, useState } from 'react';

import {
  buildGroundingLearningIndex,
  getGroundingSources,
  getGroundingLearningRecommendation,
  getGroundingLearningStatus,
  inspectGroundingLearningIndex,
  searchGroundingLearningContext,
  uploadGroundingDocuments,
  uploadGroundingText,
} from '../api';
import type {
  GroundingIndexMode,
  GroundingLearningIndexPayload,
  GroundingLearningRecommendation,
  GroundingLearningSearchResult,
  GroundingLearningStatus,
  GroundingSource,
} from '../types';

const preparationSteps = [
  {
    title: 'Question setup',
    detail: 'Preparation Mode receives the selected role, one skill, difficulty, interview type, and optional company or grounded context.',
  },
  {
    title: 'Answer submitted',
    detail: 'The user writes an answer or submits code. The question, expected points, rubric, and answer are sent to the evaluator.',
  },
  {
    title: 'Strategy selected',
    detail: 'The system chooses rubric, test-based, or grounded scoring based on the question type and skill.',
  },
  {
    title: 'Structured evaluation',
    detail: 'The LLM explains strengths, weaknesses, missing points, and awards category scores.',
  },
  {
    title: 'Final score calculated',
    detail: 'The app calculates the final score from the score breakdown. The LLM does not directly invent the final score.',
  },
];

const adaptiveSteps = [
  {
    title: 'Build learner profile',
    detail: 'The system compares the CV with the selected job role and creates skill priorities from matched and missing skills.',
  },
  {
    title: 'Choose next skill',
    detail: 'Adaptive Mode starts from the highest-priority weak skill by default, or a strong skill if the user selects that option.',
  },
  {
    title: 'Ask and score',
    detail: 'The answer is evaluated with the same scoring engine used in Preparation Mode.',
  },
  {
    title: 'Update profile',
    detail: 'The skill score changes after feedback, so the learner profile becomes more accurate over time.',
  },
  {
    title: 'Adapt path',
    detail: 'Weak answers trigger reinforcement. Strong answers move the learner to harder or higher-priority skills.',
  },
];

const scoreCategories = [
  ['Technical correctness', 'Checks whether the answer is technically right and avoids false claims.', '4.0 points'],
  ['Completeness', 'Checks whether the answer covers the expected points and important details.', '2.5 points'],
  ['Communication', 'Checks clarity, structure, and how interview-ready the explanation sounds.', '1.5 points'],
  ['Examples', 'Rewards concrete examples, project links, or practical demonstrations.', '2.0 points'],
  ['Code quality', 'Used for coding questions to assess readability, edge cases, and maintainability.', 'up to 3.5 points'],
];

const strategyCards = [
  {
    label: 'Rubric scoring',
    when: 'Python theory, SQL theory, ML basics, behavioral, project, and general interview questions.',
    flow: 'Expected points + rubric + answer -> LLM evaluation -> app-calculated score.',
  },
  {
    label: 'Test-based scoring',
    when: 'Python coding questions with test cases. SQL is future-ready but not executed unless a safe SQL runner exists.',
    flow: 'Code -> runner -> stdout/stderr/test results -> LLM feedback -> score capped by execution quality.',
  },
  {
    label: 'Grounded scoring',
    when: 'Framework docs, uploaded learning material, internal architecture, policy, or company-specific knowledge.',
    flow: 'Question -> FAISS retrieval -> grounded context -> LLM checks answer against sources -> app-calculated score.',
  },
];

const strategyRules = [
  {
    condition: 'question.is_coding is true AND skill is Python or SQL',
    result: 'test_based',
    meaning: 'The answer is treated as a coding answer. Python can be executed against tests; SQL is kept rubric-based until a safe SQL runner exists.',
  },
  {
    condition: 'question.requires_grounding is true OR skill is a grounded/framework/internal topic',
    result: 'grounded',
    meaning: 'The answer must be checked against retrieved FAISS context from uploaded or verified material.',
  },
  {
    condition: 'None of the above rules match',
    result: 'rubric',
    meaning: 'The answer is evaluated with expected points, rubric, and category score breakdown.',
  },
];

const flagSources = [
  {
    flag: 'question_type',
    source: 'Generated by the LLM from the selected interview type.',
    check: 'Backend rejects the question if type does not match the requested mode.',
  },
  {
    flag: 'is_coding',
    source: 'Generated by the LLM, guided by the prompt. Coding interview type requires true; theory/project/behavioral require false.',
    check: 'Backend validates that is_coding matches question_type before accepting the question.',
  },
  {
    flag: 'requires_grounding',
    source: 'Set by backend when Grounded material is selected, or when the skill is a known grounded topic.',
    check: 'Evaluation selector uses this flag to choose grounded scoring.',
  },
  {
    flag: 'test_cases',
    source: 'Added by backend for common Python coding questions when templates are available.',
    check: 'Test-based scoring runs these cases before asking the LLM to evaluate code quality and explanation.',
  },
];

const criteriaFlow = [
  {
    title: 'LLM drafts question criteria',
    detail: 'The generated question includes expected_points and scoring_rubric in structured JSON.',
  },
  {
    title: 'Backend validates the question',
    detail: 'The backend checks skill, difficulty, question type, coding flag, duplicates, and off-topic criteria.',
  },
  {
    title: 'Backend checks Python templates',
    detail: 'For common Python topics, the backend calls python_expected_point_template().',
  },
  {
    title: 'Template match found',
    detail: 'Replace LLM expected_points and scoring_rubric with hardcoded trusted criteria and set criteria_source to template.',
  },
  {
    title: 'No template match',
    detail: 'Keep the LLM expected_points and scoring_rubric and leave criteria_source as llm.',
  },
];

const ragIndexSteps = [
  {
    title: 'Upload verified material',
    detail: 'Admin or user uploads PDF, TXT, MD, or XML files into data/grounding/documents.',
    file: 'backend/interview/grounding_index.py',
  },
  {
    title: 'Choose index mode',
    detail: 'use_existing loads FAISS, recreate rebuilds everything, update adds new or changed documents.',
    file: 'ensure_grounding_index()',
  },
  {
    title: 'Read documents',
    detail: 'The backend loads supported files and wraps readable text as LangChain Document objects.',
    file: 'langchain_core.documents.Document',
  },
  {
    title: 'Chunk text',
    detail: 'Documents are split into smaller passages with the same LangChain text splitting pipeline.',
    file: 'RecursiveCharacterTextSplitter',
  },
  {
    title: 'Create embeddings',
    detail: 'Each chunk is converted into a HuggingFace embedding vector using all-MiniLM-L6-v2.',
    file: 'HuggingFaceEmbeddings sentence-transformers/all-MiniLM-L6-v2',
  },
  {
    title: 'Store FAISS index',
    detail: 'Vectors and metadata are saved locally under data/grounding/faiss_index.',
    file: 'FAISS.save_local()',
  },
];

const ragQuestionSteps = [
  {
    title: 'User selects Grounded material',
    detail: 'Normal LLM generation stays off. RAG is used only when the user explicitly selects grounded material.',
  },
  {
    title: 'Build retrieval query',
    detail: 'The query is created from role, selected skill, and optional grounding query.',
  },
  {
    title: 'Retrieve top chunks',
    detail: 'FAISS returns the most relevant chunks and source filenames.',
  },
  {
    title: 'Generate grounded question',
    detail: 'The LLM receives selected skill plus retrieved context and must generate only source-supported content.',
  },
  {
    title: 'Store grounding metadata',
    detail: 'Question stores generation_strategy=grounded, requires_grounding=true, and grounding_used sources.',
  },
];

const ragEvaluationSteps = [
  {
    title: 'Answer submitted',
    detail: 'The evaluator sees requires_grounding=true on the question.',
  },
  {
    title: 'Retrieve context again',
    detail: 'The backend retrieves relevant chunks for the question and answer evaluation.',
  },
  {
    title: 'Evaluate against sources',
    detail: 'The LLM checks the answer against retrieved context, expected points, and rubric.',
  },
  {
    title: 'Penalize unsupported claims',
    detail: 'Contradictions or claims not supported by the documents should reduce the score.',
  },
  {
    title: 'Calculate final score',
    detail: 'The app still calculates the final score from score_breakdown.',
  },
];

const defaultGroundingText = `LangGraph is a framework for building stateful, multi-step AI agent workflows. It is useful when an application needs controlled reasoning steps, durable state, tool calls, human review, retries, and graph-based coordination between nodes. In a grounded interview setting, questions should focus on concepts present in the provided material, such as state, nodes, edges, checkpoints, tools, and workflow reliability.`;

const workedExamples = [
  {
    title: 'Rubric scoring example',
    skill: 'Python',
    strategy: 'Rubric scoring',
    question: 'What is the difference between json.loads() and json.load() in Python?',
    instruction: 'Explain when you would use each one and give a small practical example.',
    answer:
      'json.loads() parses JSON from a string, for example an API response body. json.load() parses JSON from a file object opened with open(). Both convert JSON into Python objects like dictionaries or lists.',
    strategyNote:
      'This is Python theory, not a coding execution task, so the system does not run tests. It asks the LLM for structured feedback and then calculates the score from the breakdown.',
    expectedPoints: [
      'Explain that json.loads() parses a JSON string.',
      'Explain that json.load() reads JSON from a file-like object.',
      'Give a practical API or file-handling example.',
      'Mention that both return Python objects such as dict or list.',
    ],
    feedback:
      'Strong answer. It correctly identifies string input for json.loads() and file-like input for json.load(). It could be stronger with a tiny code snippet and a note about invalid JSON errors.',
    finalScore: '8.4 / 10',
    formula: '3.5 + 2.0 + 1.4 + 1.5 + 0 = 8.4',
    nextStep: 'Move forward',
    nextStepReason:
      'Because the score is above 8, Adaptive Mode can move to a harder Python question or the next priority skill.',
    scoreBreakdown: [
      ['Technical correctness', '3.5 / 4.0', 'Correctly explains string vs file input and return objects.'],
      ['Completeness', '2.0 / 2.5', 'Covers the main difference but could mention error handling.'],
      ['Communication', '1.4 / 1.5', 'Clear and interview-friendly explanation.'],
      ['Examples', '1.5 / 2.0', 'Gives examples, but they are short.'],
      ['Code quality', '0 / 0', 'Not a coding implementation question.'],
    ],
  },
  {
    title: 'Test-based scoring example',
    skill: 'Python coding',
    strategy: 'Test-based scoring',
    question: 'Write a Python function that returns only the even numbers from a list of integers.',
    instruction: 'Use a list comprehension and keep the function simple.',
    answer:
      'def get_even_numbers(numbers):\n    return [number for number in numbers if number % 2 == 0]',
    strategyNote:
      'This is a Python coding question, so the system runs available test cases first. The execution result is passed into the LLM evaluator, then the app calculates the final score from the score breakdown.',
    expectedPoints: [
      'Defines a reusable function.',
      'Uses list comprehension correctly.',
      'Filters numbers using modulo logic.',
      'Handles empty lists and mixed even/odd values.',
    ],
    feedback:
      'The code passes the example tests and is readable. It could mention type expectations or add a short docstring for maintainability.',
    finalScore: '9.1 / 10',
    formula: '2.8 + 1.8 + 0.9 + 0.3 + 3.3 = 9.1',
    nextStep: 'Increase difficulty',
    nextStepReason:
      'Because the coding answer passes tests and scores above 8, Adaptive Mode can ask a harder Python coding question.',
    scoreBreakdown: [
      ['Technical correctness', '2.8 / 3.0', 'The filtering logic is correct and test cases pass.'],
      ['Completeness', '1.8 / 2.0', 'The function covers the requested behavior.'],
      ['Communication', '0.9 / 1.0', 'Answer is concise and understandable.'],
      ['Examples', '0.3 / 0.5', 'No explicit example call was included.'],
      ['Code quality', '3.3 / 3.5', 'Readable, efficient, and idiomatic list comprehension.'],
    ],
  },
  {
    title: 'Grounded scoring example',
    skill: 'LangChain',
    strategy: 'Grounded scoring',
    question: 'According to the uploaded LangChain material, when should you use a retriever in a RAG pipeline?',
    instruction: 'Answer only from the grounded material and avoid unsupported claims.',
    answer:
      'A retriever should be used when the application needs to find relevant document chunks for a user query before passing context to the model. It helps ground the response in source material instead of relying only on model memory.',
    strategyNote:
      'This question requires verified material. The system retrieves relevant FAISS chunks, gives them to the evaluator, and asks the LLM to penalize contradictions or unsupported claims.',
    expectedPoints: [
      'Mention retrieving relevant chunks or documents for a query.',
      'Explain that retrieved context is passed to the model.',
      'Connect retrieval to grounded or source-backed responses.',
      'Avoid claims not supported by the uploaded material.',
    ],
    feedback:
      'Good grounded answer. It matches the retrieved material and avoids unsupported details. It could improve by naming the specific source or describing how top-k retrieval affects context selection.',
    finalScore: '8.2 / 10',
    formula: '3.4 + 2.1 + 1.2 + 1.5 + 0 = 8.2',
    nextStep: 'Ask a deeper grounded question',
    nextStepReason:
      'Because the answer is strong but not perfect, Adaptive Mode can ask a follow-up on retrieval quality or chunk selection.',
    scoreBreakdown: [
      ['Technical correctness', '3.4 / 4.0', 'Answer aligns with retrieved context and avoids contradictions.'],
      ['Completeness', '2.1 / 2.5', 'Covers retrieval and grounding, but misses retrieval configuration details.'],
      ['Communication', '1.2 / 1.5', 'Clear explanation with good structure.'],
      ['Examples', '1.5 / 2.0', 'Practical RAG context is present, but source-specific detail is limited.'],
      ['Code quality', '0 / 0', 'Not a coding implementation question.'],
    ],
  },
];

function readableSeparator(separator: string) {
  if (separator === '\\n\\n') return 'paragraph break \\n\\n';
  if (separator === '\\n') return 'line break \\n';
  if (separator === ' ') return 'space';
  return 'individual characters';
}

function VectorStats({ vector }: { vector: { dimensions: number; magnitude: number; minimum: number; maximum: number; non_zero_values: number; first_16_values: number[] } }) {
  return (
    <div className="vector-stats">
      {[
        [vector.dimensions, 'dimensions'],
        [vector.magnitude, 'magnitude'],
        [vector.minimum, 'minimum value'],
        [vector.maximum, 'maximum value'],
        [vector.non_zero_values, 'non-zero values'],
      ].map(([value, label]) => (
        <div key={label}>
          <strong>{value}</strong>
          <span>{label}</span>
        </div>
      ))}
      <code>[{vector.first_16_values.join(', ')} ...]</code>
    </div>
  );
}

export function LearningScoringPage() {
  const [activeLearning, setActiveLearning] = useState<'interview_scoring' | 'rag_learning'>('interview_scoring');
  const [groundingIndexMode, setGroundingIndexMode] = useState<GroundingIndexMode>('use_existing');
  const [groundingSources, setGroundingSources] = useState<GroundingSource[]>([]);
  const [learningStatus, setLearningStatus] = useState<GroundingLearningStatus | null>(null);
  const [learningRecommendation, setLearningRecommendation] = useState<GroundingLearningRecommendation | null>(null);
  const [learningIndex, setLearningIndex] = useState<GroundingLearningIndexPayload | null>(null);
  const [learningSearch, setLearningSearch] = useState<GroundingLearningSearchResult | null>(null);
  const [pastedGroundingText, setPastedGroundingText] = useState(defaultGroundingText);
  const [pastedFilename, setPastedFilename] = useState('rag_learning_sample.txt');
  const [retrievalQuery, setRetrievalQuery] = useState('LangGraph stateful agent workflow reliability');
  const [retrievalTopK, setRetrievalTopK] = useState(3);
  const [maximumL2Distance, setMaximumL2Distance] = useState(1.2);
  const [showGroundingSources, setShowGroundingSources] = useState(false);
  const [showVectorPreview, setShowVectorPreview] = useState(false);
  const [showRetrievedContext, setShowRetrievedContext] = useState(false);
  const [showSavedFiles, setShowSavedFiles] = useState(false);
  const [chunkSize, setChunkSize] = useState(220);
  const [chunkOverlap, setChunkOverlap] = useState(40);
  const [loadingLabel, setLoadingLabel] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    if (activeLearning !== 'rag_learning') return;
    refreshGroundingSources();
  }, [activeLearning]);

  async function refreshGroundingSources() {
    await runGroundingTask('Loading grounding sources', async () => {
      const [sources, status, recommendation] = await Promise.all([
        getGroundingSources(),
        getGroundingLearningStatus(),
        getGroundingLearningRecommendation(chunkSize, chunkOverlap),
      ]);
      setGroundingSources(sources);
      setLearningStatus(status);
      setLearningRecommendation(recommendation);
    });
  }

  async function uploadGroundingFiles(event: ChangeEvent<HTMLInputElement>) {
    if (!event.target.files?.length) return;
    await runGroundingTask('Uploading grounding documents', async () => {
      setGroundingSources(await uploadGroundingDocuments(event.target.files!));
      setLearningRecommendation(await getGroundingLearningRecommendation(chunkSize, chunkOverlap));
      setGroundingIndexMode('update');
    });
    event.target.value = '';
  }

  async function savePastedGroundingText() {
    if (!pastedGroundingText.trim()) return;
    await runGroundingTask('Saving pasted grounding text', async () => {
      const result = await uploadGroundingText(pastedGroundingText.trim(), pastedFilename.trim() || 'pasted_grounding_material.txt');
      setGroundingSources(result.sources);
      setLearningRecommendation(await getGroundingLearningRecommendation(chunkSize, chunkOverlap));
      setGroundingIndexMode('update');
      setShowGroundingSources(true);
    });
  }

  async function prepareGroundingIndex() {
    await runGroundingTask('Preparing grounding index', async () => {
      const result = await buildGroundingLearningIndex(groundingIndexMode, chunkSize, chunkOverlap);
      setLearningIndex(result);
      setLearningStatus(await getGroundingLearningStatus());
      setLearningRecommendation(await getGroundingLearningRecommendation(chunkSize, chunkOverlap));
      setGroundingSources(await getGroundingSources());
      setShowGroundingSources(true);
      setShowVectorPreview(true);
    });
  }

  async function inspectExistingIndex() {
    await runGroundingTask('Inspecting existing FAISS index', async () => {
      setLearningIndex(await inspectGroundingLearningIndex());
      setLearningStatus(await getGroundingLearningStatus());
      setShowVectorPreview(true);
    });
  }

  async function refreshRecommendation() {
    await runGroundingTask('Checking index recommendation', async () => {
      setLearningRecommendation(await getGroundingLearningRecommendation(chunkSize, chunkOverlap));
      setLearningStatus(await getGroundingLearningStatus());
    });
  }

  async function previewRetrievedContext() {
    if (!retrievalQuery.trim()) return;
    await runGroundingTask('Retrieving context for LLM prompt', async () => {
      setLearningSearch(await searchGroundingLearningContext(retrievalQuery.trim(), retrievalTopK, maximumL2Distance));
      setShowRetrievedContext(true);
    });
  }

  async function runGroundingTask(label: string, task: () => Promise<void>) {
    setError('');
    setLoadingLabel(label);
    try {
      await task();
    } catch (caughtError) {
      setError(caughtError instanceof Error ? caughtError.message : 'Grounding operation failed.');
    } finally {
      setLoadingLabel('');
    }
  }

  return (
    <>
      <section className="topbar learning-hero">
        <div>
          <p className="eyebrow">Learning & Scoring</p>
          <h1>How HireReadyAI scores answers and adapts interview practice</h1>
          <p className="muted-line">
            This page is a visual guide to what happens after a user answers an interview question.
          </p>
        </div>
      </section>

      <section className="learning-option-grid" aria-label="Learning sections">
        <button
          className={activeLearning === 'interview_scoring' ? 'active' : ''}
          type="button"
          onClick={() => setActiveLearning('interview_scoring')}
        >
          <span>Learning option</span>
          <strong>Interview scoring</strong>
          <small>Understand interview rubric, test-based, grounded evaluation, and final score calculation.</small>
        </button>
        <button
          className={activeLearning === 'rag_learning' ? 'active' : ''}
          type="button"
          onClick={() => setActiveLearning('rag_learning')}
        >
          <span>Learning option</span>
          <strong>RAG learning</strong>
          <small>See what happens inside grounded documents: upload, chunk, embed, retrieve, generate, evaluate.</small>
        </button>
      </section>

      {activeLearning === 'rag_learning' && <section className="panel learning-score-wide">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Model-powered RAG Learning Lab</p>
            <h2>Inside HuggingFace embeddings, LangChain chunking, and FAISS</h2>
            <p className="muted-line">This lab uses the real grounding store in <code>data/grounding</code>, not a separate demo vector database.</p>
          </div>
        </div>

        <div className="rag-learning-band">
          <div><span>Important</span><strong>No LLM call here</strong><p>Indexing uses chunking, embeddings, and FAISS only. LLMs are called later during grounded question generation or scoring.</p></div>
          <div><span>Vector store</span><strong>data/grounding/faiss_index</strong><p>The same index is used by Interview Preparation and Adaptive Interview when Grounded material is selected.</p></div>
          <div><span>Encoder</span><strong>all-MiniLM-L6-v2</strong><p>Chunks and questions are embedded separately into the same 384-dimensional semantic vector space.</p></div>
        </div>

        <div className="rag-control-panel model-rag-lab">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">1</p>
              <h3>Index a document with the real model</h3>
            </div>
          </div>

          <div className="input-options">
            <article><strong>Option 1: Default example</strong><p>Restore the included teaching text.</p><button className="ghost-button" type="button" onClick={() => setPastedGroundingText(defaultGroundingText)}>Use default text</button></article>
            <article><strong>Option 2: Copy and paste</strong><p>Paste or type directly in the editable document area, then save it as a grounding document.</p></article>
            <article><strong>Option 3: Upload documents</strong><p>Choose one or more PDF, TXT, MD, or XML files. The app stores them under data/grounding/documents.</p><label className="file-control">Upload<input accept=".pdf,.txt,.md,.xml" multiple type="file" onChange={uploadGroundingFiles} /></label></article>
          </div>

          <div className="source-status source-status-row">
            <span>Current grounding store: {groundingSources.length} document(s) in data/grounding/documents</span>
            <button className="ghost-button" type="button" onClick={refreshGroundingSources} disabled={Boolean(loadingLabel)}>
              Refresh folder state
            </button>
          </div>

          <div className="rag-paste-panel">
            <div className="panel-heading">
              <div>
                <p className="eyebrow">Editable document text</p>
                <h3>Paste text into the grounding document store</h3>
              </div>
              <button className="ghost-button" type="button" onClick={savePastedGroundingText} disabled={!pastedGroundingText.trim() || Boolean(loadingLabel)}>
                Save text document
              </button>
            </div>
            <label className="field-label">
              Filename
              <input className="number-input" value={pastedFilename} onChange={(event) => setPastedFilename(event.target.value)} />
            </label>
            <textarea className="short-textarea" value={pastedGroundingText} onChange={(event) => setPastedGroundingText(event.target.value)} />
          </div>

          <div className="lifecycle-box">
            <h3>Choose what to do with the vector database</h3>
            <div className="operation-options">
              {(['use_existing', 'recreate', 'update'] as GroundingIndexMode[]).map((mode) => (
                <label key={mode}>
                  <input checked={groundingIndexMode === mode} name="learningIndexMode" type="radio" value={mode} onChange={() => setGroundingIndexMode(mode)} />
                  <span>
                    <strong>{mode.replace('_', ' ')}</strong>
                    {mode === 'use_existing' && 'Load saved vectors without chunking or embedding again.'}
                    {mode === 'recreate' && 'Delete the saved index and rebuild every supplied document.'}
                    {mode === 'update' && 'Hash documents, skip duplicates, and index new or changed documents.'}
                  </span>
                </label>
              ))}
            </div>
            <div className={`recommendation recommendation-${learningRecommendation?.recommended_operation ?? 'recreate'}`}>
              <strong>Suggested: {(learningRecommendation?.recommended_operation ?? 'recreate').replace('_', ' ')}</strong>
              <span>{learningRecommendation?.reason ?? 'Checking saved vector database...'}</span>
            </div>
            <div className="helper-callout">
              Recreate rebuilds the FAISS index from every supported file currently inside <strong>data/grounding/documents</strong>. If a deleted file still appears here, click <strong>Refresh folder state</strong> first.
            </div>
            {learningStatus && <div className="registry">
              <div className="registry-heading">
                <strong>Saved document registry</strong>
                <span>{learningStatus.documents.length} document(s) · last updated {learningStatus.updated_at ?? 'unknown'}</span>
              </div>
              {learningStatus.documents.length > 0 ? (
                <div className="table-scroll"><table><thead><tr><th>Filename</th><th>SHA-256 hash</th><th>Chunks</th><th>Indexed at</th></tr></thead><tbody>
                  {learningStatus.documents.map((document) => (
                    <tr key={document.filename}><td>{document.filename}</td><td><code>{document.file_hash}</code></td><td>{document.chunk_count}</td><td>{document.indexed_at}</td></tr>
                  ))}
                </tbody></table></div>
              ) : <p className="muted-line">No document registry entries yet.</p>}
            </div>}
          </div>

          <div className="rag-chunk-grid">
            <label className="field-label">Chunk size in characters<input className="number-input" max={4000} min={200} step={10} type="number" value={chunkSize} onChange={(event) => setChunkSize(Number(event.target.value))} onBlur={refreshRecommendation} /></label>
            <label className="field-label">Overlap in characters<input className="number-input" max={1000} min={0} step={10} type="number" value={chunkOverlap} onChange={(event) => setChunkOverlap(Number(event.target.value))} onBlur={refreshRecommendation} /></label>
            <div className="button-row">
              <button className="primary-button" type="button" onClick={prepareGroundingIndex} disabled={Boolean(loadingLabel)}>Run selected indexing operation</button>
              <button className="ghost-button" type="button" onClick={inspectExistingIndex} disabled={Boolean(loadingLabel)}>Inspect existing</button>
            </div>
          </div>

          {loadingLabel && <div className="status loading">{loadingLabel}...</div>}
          {error && <div className="status error">{error}</div>}
        </div>

        {learningIndex && <>
          <section className="rag-learning-section">
            <div className="panel-heading"><div><p className="eyebrow">2</p><h3>Model and indexing steps</h3></div></div>
            <div className="stats-grid">
              {[
                [String(learningIndex.model.name ?? '-'), 'embedding model'],
                [String(learningIndex.model.dimensions ?? '-'), 'vector dimensions'],
                [String(learningIndex.splitter.chunk_count ?? '-'), 'created chunks'],
                [String(learningIndex.faiss.index_class ?? '-'), 'FAISS index class'],
                [String(learningIndex.faiss.metric_type ?? '-'), 'distance metric'],
                [String(learningIndex.faiss.total_vectors ?? '-'), 'stored vectors'],
              ].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}
            </div>
            <div className="rag-step-grid">{learningIndex.indexing_steps.map((step, index) => <article key={step}><span>{index + 1}</span><p>{step}</p></article>)}</div>
          </section>

          <section className="rag-learning-section">
            <div className="panel-heading"><div><p className="eyebrow">3</p><h3>Recursive chunking steps</h3></div><span className="score-badge">{learningIndex.records.length} chunks</span></div>
            <div className="split-explanation">
              <h3>Separators tried in order</h3>
              <div className="separators">{(learningIndex.splitter.separators_tried_in_order as string[] ?? []).map((separator, index) => <span key={`${separator}-${index}`}><b>{index + 1}</b>{readableSeparator(separator)}</span>)}</div>
              <p>{String(learningIndex.splitter.how_it_works ?? '')}</p>
            </div>
            <div className="chunking-records">
              {learningIndex.records.map((record) => (
                <article className="chunking-card" key={record.document_id}>
                  <div className="chunk-range"><strong>Chunk {record.faiss_position}</strong><span>{String(record.metadata.source ?? 'unknown')}</span><span>characters {record.chunking.start_character}-{record.chunking.end_character}</span><span>{record.chunking.character_count} characters</span></div>
                  {record.chunking.overlap_character_count > 0 ? <div className="overlap"><strong>Repeated from previous chunk ({record.chunking.overlap_character_count} characters)</strong><code>{record.chunking.overlap_text}</code></div> : <div className="overlap no-overlap">First chunk has no previous overlap.</div>}
                  <p>{record.text}</p>
                </article>
              ))}
            </div>
          </section>

          <section className="rag-learning-section">
            <div className="panel-heading"><div><p className="eyebrow">4</p><h3>Chunk tokens and semantic embeddings</h3></div></div>
            <div className="rag-preview-actions">
              <button className="ghost-button" type="button" onClick={() => setShowVectorPreview((value) => !value)}>{showVectorPreview ? 'Hide token/vector records' : 'Show token/vector records'}</button>
              <button className="ghost-button" type="button" onClick={() => setShowSavedFiles((value) => !value)}>{showSavedFiles ? 'Hide saved FAISS files' : 'Show saved FAISS files'}</button>
            </div>
            {showVectorPreview && <div className="records-grid">{learningIndex.records.map((record) => <article className="record-card" key={`vector-${record.document_id}`}><div className="record-title"><strong>FAISS position {record.faiss_position}</strong><code>{record.document_id}</code></div><p>{record.text}</p><div className="metadata">Metadata: <code>{JSON.stringify(record.metadata)}</code></div><details><summary>Tokenizer output: {record.tokenization.tokens.length} tokens</summary><div className="tokens">{record.tokenization.tokens.map((token, index) => <span key={`${record.document_id}-${token}-${index}`} title={`ID ${record.tokenization.token_ids[index]}`}>{token}</span>)}</div></details><details><summary>384-dimensional semantic embedding</summary><VectorStats vector={record.vector} /><p className="muted-line">Individual dimensions do not correspond to named words. Meaning is distributed across the full vector.</p></details><div className="coordinate">2D teaching projection: ({record.pca_2d.join(', ')})</div></article>)}</div>}
          </section>

          {showSavedFiles && <section className="rag-learning-section">
            <div className="panel-heading"><div><p className="eyebrow">5</p><h3>What FAISS and LangChain store</h3></div></div>
            <div className="file-grid">{Object.entries(learningIndex.saved_files).map(([key, file]) => <article className="file-card" key={key}><strong>{file.path.split('/').pop()}</strong><span>{file.size_bytes} bytes</span><p>{file.stores}</p>{file.does_not_store && <p className="warning">Does not store: {file.does_not_store}</p>}{file.security_note && <p className="warning">{file.security_note}</p>}<details><summary>Show details</summary><pre>{JSON.stringify(file.details, null, 2)}</pre></details></article>)}</div>
            <h3>FAISS position {'->'} LangChain document mapping</h3>
            <div className="table-scroll"><table><thead><tr><th>FAISS position</th><th>Document ID</th><th>Metadata</th><th>Text</th></tr></thead><tbody>{learningIndex.records.map((record) => <tr key={`map-${record.document_id}`}><td>{record.faiss_position}</td><td><code>{record.document_id}</code></td><td><code>{JSON.stringify(record.metadata)}</code></td><td>{record.text}</td></tr>)}</tbody></table></div>
          </section>}
        </>}

        <div className="rag-retrieval-panel">
          <div className="panel-heading"><div><p className="eyebrow">6</p><h3>Embed a question and search FAISS</h3><p className="muted-line">Try a paraphrase whose exact words do not appear in the document.</p></div></div>
          <div className="rag-retrieval-grid model-search-grid">
            <label className="field-label">Question<input className="number-input" value={retrievalQuery} onChange={(event) => setRetrievalQuery(event.target.value)} /></label>
            <label className="field-label">Top K<input className="number-input" max={10} min={1} type="number" value={retrievalTopK} onChange={(event) => setRetrievalTopK(Number(event.target.value))} /></label>
            <label className="field-label">Maximum L2 distance<input className="number-input" max={10} min={0} step={0.1} type="number" value={maximumL2Distance} onChange={(event) => setMaximumL2Distance(Number(event.target.value))} /></label>
            <button className="ghost-button" type="button" onClick={previewRetrievedContext} disabled={!retrievalQuery.trim() || Boolean(loadingLabel)}>Embed question and retrieve</button>
          </div>
          {showRetrievedContext && learningSearch && <div className="search-learning-results">
            <div className="stats-grid">{[[learningSearch.tokenization.tokens.length, 'question tokens'], [learningSearch.query_vector.dimensions, 'embedding dimensions'], [learningSearch.query_vector.magnitude, 'query magnitude'], [learningSearch.nearest_neighbors.length, 'nearest neighbors returned'], [learningSearch.results.length, 'neighbors accepted as relevant']].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
            <h3>Question tokens</h3>
            <div className="tokens">{learningSearch.tokenization.tokens.map((token, index) => <span key={`${token}-${index}`}>{token}</span>)}</div>
            <h3>Retrieval steps</h3>
            <div className="rag-step-grid">{learningSearch.retrieval_steps.map((step, index) => <article key={step}><span>{index + 1}</span><p>{step}</p></article>)}</div>
            <div className={`decision ${learningSearch.has_relevant_context ? 'decision-accept' : 'decision-reject'}`}><strong>{learningSearch.has_relevant_context ? 'Relevant context accepted' : 'No relevant context found'}</strong><p>{learningSearch.retrieval_decision}</p><small>FAISS always returns nearest vectors. The distance threshold decides whether they are relevant enough for an LLM.</small></div>
            <div className="results-grid">{learningSearch.nearest_neighbors.map((result) => <article className={result.l2_distance <= learningSearch.maximum_l2_distance ? 'accepted-result' : 'rejected-result'} key={`${result.rank}-${result.document_id}`}><div className="rank">Rank {result.rank}</div><h3>FAISS position {result.faiss_position}</h3><div className="distance">Squared L2 distance: <strong>{result.l2_distance}</strong></div><code>Manual check sum(query_i - chunk_i)^2 = {result.manual_squared_l2}</code><p>{result.text}</p><div className="result-decision">{result.l2_distance <= learningSearch.maximum_l2_distance ? 'Accepted as relevant' : 'Rejected as too distant'}</div><small>LangChain document ID: {result.document_id}</small></article>)}</div>
            <div className="context-preview"><h3>Context that would be sent to Mistral or another LLM</h3><pre>{learningSearch.context_for_llm || "No context sent to the LLM. Safe answer: I don't know based on the indexed document."}</pre></div>
          </div>}
        </div>

        <div className="rag-learning-section">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Step 1</p>
              <h3>Build or update the FAISS index</h3>
            </div>
          </div>
          <div className="rag-step-grid">
            {ragIndexSteps.map((step, index) => (
              <article key={step.title}>
                <span>{String(index + 1).padStart(2, '0')}</span>
                <strong>{step.title}</strong>
                <p>{step.detail}</p>
                <small>{step.file}</small>
              </article>
            ))}
          </div>
        </div>

        <div className="rag-learning-section">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Step 2</p>
              <h3>Generate grounded questions</h3>
            </div>
          </div>
          <div className="rag-flow-list">
            {ragQuestionSteps.map((step, index) => (
              <article key={step.title}>
                <span>{String(index + 1).padStart(2, '0')}</span>
                <div>
                  <strong>{step.title}</strong>
                  <p>{step.detail}</p>
                </div>
              </article>
            ))}
          </div>
        </div>

        <div className="rag-learning-section">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Step 3</p>
              <h3>Score grounded answers</h3>
            </div>
          </div>
          <div className="rag-flow-list">
            {ragEvaluationSteps.map((step, index) => (
              <article key={step.title}>
                <span>{String(index + 1).padStart(2, '0')}</span>
                <div>
                  <strong>{step.title}</strong>
                  <p>{step.detail}</p>
                </div>
              </article>
            ))}
          </div>
        </div>

        <div className="strategy-code-note">
          <strong>Backend sources</strong>
          <code>backend/interview/grounding_index.py</code>
          <code>backend/interview/grounding_retriever.py</code>
          <code>backend/interview/preparation_interview.py</code>
          <code>backend/interview/interview_assistant.py</code>
        </div>
      </section>}

      {activeLearning === 'interview_scoring' && <>
      <section className="learning-score-grid">
        <article className="panel learning-score-panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Preparation Mode</p>
              <h2>User-guided focused practice</h2>
            </div>
          </div>
          <div className="learning-flow">
            {preparationSteps.map((step, index) => (
              <div key={step.title} className="learning-flow-step">
                <span>{String(index + 1).padStart(2, '0')}</span>
                <div>
                  <strong>{step.title}</strong>
                  <small>{step.detail}</small>
                </div>
              </div>
            ))}
          </div>
        </article>

        <article className="panel learning-score-panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Adaptive Mode</p>
              <h2>System-guided skill diagnosis</h2>
            </div>
          </div>
          <div className="learning-flow">
            {adaptiveSteps.map((step, index) => (
              <div key={step.title} className="learning-flow-step">
                <span>{String(index + 1).padStart(2, '0')}</span>
                <div>
                  <strong>{step.title}</strong>
                  <small>{step.detail}</small>
                </div>
              </div>
            ))}
          </div>
        </article>
      </section>

      <section className="learning-score-grid">
        <article className="panel settings-wide">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Scoring Strategies</p>
              <h2>One evaluator, three paths</h2>
            </div>
          </div>
          <div className="learning-strategy-grid">
            {strategyCards.map((strategy) => (
              <div key={strategy.label} className="learning-strategy-card">
                <strong>{strategy.label}</strong>
                <span>When used</span>
                <p>{strategy.when}</p>
                <span>Flow</span>
                <p>{strategy.flow}</p>
              </div>
            ))}
          </div>
        </article>
      </section>

      <section className="panel learning-score-wide">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Strategy Selector Logic</p>
            <h2>How the backend decides which evaluation strategy to use</h2>
          </div>
        </div>
        <div className="strategy-rule-flow">
          {strategyRules.map((rule, index) => (
            <article key={rule.result}>
              <span>{String(index + 1).padStart(2, '0')}</span>
              <div>
                <strong>If {rule.condition}</strong>
                <p>Use <b>{rule.result}</b></p>
                <small>{rule.meaning}</small>
              </div>
            </article>
          ))}
        </div>
        <div className="strategy-code-note">
          <strong>Backend source</strong>
          <code>backend/interview/interview_assistant.py - select_evaluation_strategy()</code>
        </div>
      </section>

      <section className="panel learning-score-wide">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Where The Flags Come From</p>
            <h2>How the system knows whether a question is coding, grounded, or rubric-based</h2>
          </div>
        </div>
        <div className="flag-source-grid">
          {flagSources.map((item) => (
            <article key={item.flag}>
              <strong>{item.flag}</strong>
              <span>Where it comes from</span>
              <p>{item.source}</p>
              <span>How it is checked</span>
              <p>{item.check}</p>
            </article>
          ))}
        </div>
        <div className="strategy-code-note">
          <strong>Generation sources</strong>
          <code>prompts/interview_preparation_question_generator.yml</code>
          <code>prompts/adaptive_interview.yml</code>
        </div>
      </section>

      <section className="panel learning-score-wide">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Expected Points & Rubric Source</p>
            <h2>When LLM criteria are kept and when hardcoded templates replace them</h2>
          </div>
        </div>
        <div className="criteria-flow">
          {criteriaFlow.map((step, index) => (
            <article key={step.title}>
              <span>{String(index + 1).padStart(2, '0')}</span>
              <div>
                <strong>{step.title}</strong>
                <p>{step.detail}</p>
              </div>
            </article>
          ))}
        </div>
        <div className="criteria-result-grid">
          <div>
            <span>criteria_source = template</span>
            <strong>Hardcoded trusted criteria used</strong>
            <p>Expected points and rubric came from expected_point_templates.py.</p>
          </div>
          <div>
            <span>criteria_source = llm</span>
            <strong>LLM criteria kept</strong>
            <p>No matching Python template was found, so the validated LLM criteria stay on the question.</p>
          </div>
        </div>
        <div className="strategy-code-note">
          <strong>Backend source</strong>
          <code>backend/interview/expected_point_templates.py</code>
          <code>backend/interview/preparation_interview.py - _validated_question()</code>
        </div>
      </section>

      <section className="panel learning-score-wide">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Worked Example</p>
            <h2>Real scoring flows for every evaluation strategy</h2>
          </div>
        </div>

        {workedExamples.map((example) => (
          <div className="learning-example-section" key={example.title}>
            <div className="learning-example-title">
              <div>
                <p className="eyebrow">{example.title}</p>
                <h3>{example.strategy}</h3>
              </div>
              <span className="skill-pill">Skill: {example.skill}</span>
            </div>

            <div className="learning-example-grid">
              <article className="learning-example-card">
                <span>Question</span>
                <strong>{example.question}</strong>
                <p>{example.instruction}</p>
              </article>

              <article className="learning-example-card">
                <span>User answer</span>
                <p>{example.answer}</p>
              </article>

              <article className="learning-example-card">
                <span>Evaluation strategy used</span>
                <strong>{example.strategy}</strong>
                <p>{example.strategyNote}</p>
              </article>
            </div>

            <div className="learning-example-grid two-column">
              <article className="learning-example-card">
                <span>Expected points</span>
                <ul>
                  {example.expectedPoints.map((point) => <li key={point}>{point}</li>)}
                </ul>
              </article>

              <article className="learning-example-card">
                <span>LLM feedback summary</span>
                <p>{example.feedback}</p>
              </article>
            </div>

            <div className="learning-example-score">
              <div>
                <span>App-calculated final score</span>
                <strong>{example.finalScore}</strong>
                <small>{example.formula}</small>
              </div>
              <div>
                <span>Adaptive next step</span>
                <strong>{example.nextStep}</strong>
                <small>{example.nextStepReason}</small>
              </div>
            </div>

            <div className="score-breakdown-grid">
              {example.scoreBreakdown.map(([name, score, reason]) => (
                <article key={name}>
                  <div>
                    <strong>{name}</strong>
                    <span>{score}</span>
                  </div>
                  <p>{reason}</p>
                </article>
              ))}
            </div>
          </div>
        ))}
      </section>

      <section className="learning-score-grid">
        <article className="panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Score Formula</p>
              <h2>Final score comes from the breakdown</h2>
            </div>
          </div>
          <div className="learning-score-equation">
            <strong>Final score</strong>
            <span>=</span>
            <small>technical correctness + completeness + communication + examples + code quality</small>
          </div>
          <p className="muted-line">
            The LLM provides structured category evidence. HireReadyAI validates that structure and calculates the final number from those categories.
          </p>
        </article>

        <article className="panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Adaptive Decision</p>
              <h2>How the next question is selected</h2>
            </div>
          </div>
          <div className="learning-decision-list">
            <div><strong>0-4.9</strong><span>Skill is weak. Ask an easier reinforcement question.</span></div>
            <div><strong>5-7.9</strong><span>Skill is developing. Ask another question to confirm understanding.</span></div>
            <div><strong>8-10</strong><span>Skill is strong. Move to a harder or higher-priority skill.</span></div>
          </div>
        </article>
      </section>

      <section className="panel learning-score-wide">
        <div className="panel-heading">
          <div>
            <p className="eyebrow">Score Breakdown</p>
            <h2>What each category means</h2>
          </div>
        </div>
        <div className="score-breakdown-grid">
          {scoreCategories.map(([name, detail, points]) => (
            <article key={name}>
              <div>
                <strong>{name}</strong>
                <span>{points}</span>
              </div>
              <p>{detail}</p>
            </article>
          ))}
        </div>
      </section>
      </>}
    </>
  );
}
